### ISSUE TITLE
Create profiles of Reference to simplify applying common constraints.

### ISSUE THREAD

**Issue by RichardTON** [AuDigitalHealth/ci-fhir-r4#18]
# Prerequisites
- [x ] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x ] I have written a descriptive issue title

# The issue / feature
## Change description
Create profiles of Reference to simplify applying common constraints. Candidate constraints are 
* At least one of reference, identifier and display SHALL be present and
* At least one of reference and identifier SHALL be present and If present, identifier SHALL have a system and a value
## What it actually enables people to do
Allows profiles to constrain use of Reference with a change of type rather than by adding invariants 

## How awesome would it be?
Profiles with a lot of references will look simpler in data hierarchies. Common constraints will be less distracting, allows readers to focus on profile specific constraints.

## Workarounds
N/A

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by robeastwood-agency** [comment]
An alternative to the creation of Reference profiles may be to use more generic FHIRPath expressions such as the core specification does for things such as element. However, an investigation is required to determine if this is a viable alternative.

**Comment by dtr-agency** [comment]
Profiles of reference were considered during development of ADHA FHIR IG v1.0.0. On review of potential approach with the FHIR Architect this approach is deemed not desirable:
1. Higher validation cost to use profile over invariant
2. Higher burden on implementer reading the specification - 'Reference' is understood; a profile name will not be and requires click through to each profile to read rather than reading the invariant string on the element.
