### ISSUE TITLE
Pathology Report with atomic content

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#21]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
The purpose of this profile is to define an atomic representation of a pathology report issued by the diagnostic service provider to support the electronic exchange of pathology reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia. 

## What it actually enables people to do
Ensure the desired behavior is applied to subject reference.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by SatyaYelisetti** [comment]
Shell profile of Atomic Pathology Report has been created and is currently under review.

**Comment by SatyaYelisetti** [comment]
Shell profile of Atomic Pathology Report has been created and it can be found at the above commit

**Comment by dtr-agency** [comment]
The ValueSet design in #61 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/pathology-diagnostic-service-category-1.

**Comment by dtr-agency** [comment]
The ValueSet design in #58 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1.

**Comment by dtr-agency** [comment]
Work started on phase 2; intending to:
- No 'work in progress' issues remain:
   - meta.profile (invariant on profile value)
   - status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1" – edited short
   - subject (Reference type too open) – fixed with invariant 
   - performer (Reference type too open) - fixed with invariant
   - category is bound as extensible – uri="https://healthterminologies.gov.au/fhir/ValueSet/pathology-diagnostic-service-category-1"
   - code is bound as extensible - uri = "https://healthterminologies.gov.au/fhir/ValueSet/pathology-procedure-1"
- The following features have been included:
   - canonical URL change (removing '4.0') has been proliferated - affects profiles Organization with Mandatory Identifier, Patient with Mandatory Identifier, My Health Record Patient, PractitionerRole with Mandatory Identifier
   - category is bound as extensible
- removed wip known issues, added status terminology publication issue 
- Added draft implementation guidance + context

**Comment by dtr-agency** [comment]
Product review leading to fixes to implementation guidance; added short to basedOn.reference. Product owner now okayed content.

**Comment by dtr-agency** [comment]
Sent for internal review with @RichardTON.

**Comment by dtr-agency** [comment]
Passed internal review.

**Comment by dtr-agency** [comment]
Merged, rebuild output, and pushed to GitHub.
