### ISSUE TITLE
Service Request - Order Details for Pathology Report

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#31]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
This profile is to represent key elements of clinical relevance of a request for a pathology diagnostic investigation in a pathology report context. This profile is intended to support the electronic exchange of pathology reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by dbojicic-agency** [comment]
This issue is in progress via internal ticket https://jira.digitalhealth.gov.au/browse/CIFMM-3397.

**Comment by dbojicic-agency** [comment]
Phase 1 shell profile Order Details for Pathology Report profile been completed. 
The shell profile has the basic structure but is missing constraints and terminology bindings. 
Profile page in Diagnostics Report FHIR IG includes a list of known issues for the profile.

**Comment by dtr-agency** [comment]
The ValueSet design in #60 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/requeststatus-reporting-1.

**Comment by dtr-agency** [comment]
- Addressed 'work in progress' issues:
  - subject (Reference type too open) - fixed with invariant
  - requester (Reference type too open)- fixed with invariant
  - status is bound as required - uri = "https://healthterminologies.gov.au/ValueSet/requeststatus-reporting-1" - also edited short to align
  - code is bound as extensible - uri = "https://healthterminologies.gov.au/fhir/ValueSet/pathology-procedure-1"
- The following features have been included:
   - canonical URL change (removing '4.0') has been proliferated - affects profiles Patient, PractitionerRole and Organization profiles
- intro.md - added draft context, purpose, implementation guidance and new boundaries and relationships heading
- Cleaned up known issues - removed addressed issues, corrected links to a couple, added content to self-initiated and program to make more suited to external audience

**Comment by dtr-agency** [comment]
Product owner walkthrough organised for 10/06.

**Comment by dtr-agency** [comment]
Minor changes from product owner review to issues and intro content. Now product owner okayed, moving to internal review with @dbojicic-agency.

**Comment by dbojicic-agency** [comment]
Starting the peer review via internal PR 63.

**Comment by dtr-agency** [comment]
Passed internal review; rebuilt Diagnostic Report output and on master to complete the profile and introductory content.
