### ISSUE TITLE
Composition - Other Diagnostic Report

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#33]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
This profile is to define a representation for the electronic exchange of reports of other diagnostic investigations (such as echo cardiogram or colonoscopy or hearing test) as a document between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia. 

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by robeastwood-agency** [comment]
Commenced work to add the phase 1 structure of this profile.

**Comment by robeastwood-agency** [comment]
The phase 1 version of the Other Diagnostic Report Composition profile has been added via https://github.com/AuDigitalHealth/ci-fhir-r4/commit/c0b0dcac1c2a33d96fbd7acd0c19d2c48ec27784

The next stage of development (not scheduled as yet) will include:
- meta.profile value enforcement
- Reference type enforcement for subject, author, custodian, attester

**Comment by dtr-agency** [comment]
The ValueSet design in #57 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/compositionstatus-document-available-1.

**Comment by dtr-agency** [comment]
Phase 2 work started. Intending to get to :
   - meta.profile (invariant on profile value)
   - status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/compositionstatus-document-available-1" – edited short
   - subject (Reference type too open) – fixed with invariant 
   - author (Reference type too open) - fixed with invariant
   - attester.party (Reference type too open) - fixed with invariant
   - custodian (Reference type too open) - fixed with invariant
- The following features have been included:
   - canonical URL change (removing '4.0') has been proliferated - affects profiles Organization with Mandatory Identifier, Patient with Mandatory Identifier, My Health Record Patient, PractitionerRole with Mandatory Identifier
- removed wip known issues, added status terminology publication issue and self-initiated request issue
- Added draft implementation guidance + context

**Comment by dtr-agency** [comment]
Product owner walkthrough resulted in minor changes to section.short, context, and implementation guidance. Product owner now okayed content.

**Comment by dtr-agency** [comment]
Moving to internal review with @RichardTON

**Comment by dtr-agency** [comment]
Passed internal review.

**Comment by dtr-agency** [comment]
Merged, regenerated, and pushed to GitHub.
