### ISSUE TITLE
Observation  - Atomic Other Diagnostic Observation

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#36]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## What it actually enables people to do
This profile is to represent an atomic representation of a other diagnostics (not pathology and not diagnostic imaging) test observation issued by the diagnostic service provider for the electronic exchange of other diagnostic test observations between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by davidmckillop** [comment]
Work has started on developing a 'shell' ( i.e. must supports, cardinality, fixed values, metadata) StructureDefinition for a Atomic Other Diagnostics Observation. Progressing content will be in a later phase 2 (i.e. slicing, terminology, invariants).

This shell profile with placeholder introductory content and early known issues will be included in Diagnostic Report FHIR IG. Progressing via CIFMM-3406.

**Comment by dtr-agency** [comment]
The ValueSet design in #59 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1.

**Comment by dtr-agency** [comment]
Atomic Other Diagnostic Observation phase 2:

- No 'work in progress' issues remain:
   - status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/observationstatus-result-available-1" – edited short
   - subject (Reference type too open) – fixed with invariant
   - performer (Reference type too open) - fixed with invariant
   - added constraint on value[x] or dataAbsentReason or hasMember - fixed with invariant
- The following features have been included: 
   - canonical URL change (removing '4.0') has been proliferated - affects profiles Organization with Mandatory Identifier, Patient with Mandatory Identifier, My Health Record Patient, PractitionerRole with Mandatory Identifier
   - removed category required pattern
   - fixed the metadata issues - removed StructureDefinition.purpose, added StructureDefinition.contact, corrected StructureDefinition.fhirVersion
   - added must support to partOf as DiagnosticImagingStudy with partOf.reference 1..1
- removed wip known issues, improved wording of remaining, added status terminology publication issue
- Added draft implementation guidance + context

**Comment by dtr-agency** [comment]
Product owner walkthrough held. Product owner okayed content.

**Comment by dtr-agency** [comment]
Sent for internal review with @RichardTON

**Comment by dtr-agency** [comment]
Review passed. Merged, regenerated, pushed to GitHub.
