### ISSUE TITLE
ServiceRequest - Order Details for Other Diagnostic Report

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#39]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
This profile is to represent key elements of clinical relevance of a request for a diagnostic investigation (such as echocardiograms) in a diagnostic report context. This profile is intended to support the electronic exchange of other diagnostic reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by robeastwood-agency** [comment]
Phase 1 shell profile Order Details for Other Diagnostic Report profile been completed. The shell profile has the basic structure but is missing constraints.

The profile page in Diagnostics Report FHIR IG includes a list of known issues for the profile.

**Comment by dtr-agency** [comment]
The ValueSet design in #60 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/requeststatus-reporting-1.

**Comment by dtr-agency** [comment]
Phase 2 work started. Intending to get to :
- No 'work in progress' issues remain:
   - status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/requeststatus-reporting-1" - edited short
   - subject (Reference type too open) - fixed with invariant
   - requester (Reference type too open) - fixed with invariant
- relaxed identifier to be optional (misalignment with eHealth Diag Report requirements)
- The canonical URL change (removing '4.0') has been proliferated in referenced profiles
- removed wip known issues, added status terminology publication issue and self-initiated request issue
- Added draft implementation guidance + context

**Comment by dtr-agency** [comment]
Product owner walkthrough teed up 17/06.

**Comment by dtr-agency** [comment]
Minor changed in product owner walkthrough to known issues and StructureDefinition.description.

**Comment by dtr-agency** [comment]
Moving to internal review with @vikasmittal-dh

**Comment by dtr-agency** [comment]
Passed internal review.

**Comment by dtr-agency** [comment]
Merged, regenerated output, pushed to GitHub.
