### ISSUE TITLE
Composition - Diagnostic Imaging Report

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#41]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
This profile is to define a representation for the electronic exchange of diagnostic imaging reports as a document between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia. 

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by LB-Agency** [comment]
Work has commenced on this profile, and as such an initial profile 'shell' is now available in the Diagnostic Report IG.

The next stage of development (not scheduled as yet) will include:

meta.profile value enforcement
Reference type enforcement for subject, author, custodian, attester
status value set - design and review
status terminology binding
intro.md narrative content

**Comment by dtr-agency** [comment]
The ValueSet design in #57 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/compositionstatus-document-available-1.

**Comment by dtr-agency** [comment]
Phase 2 work started. Intending to get to :
- No 'work in progress' issues remain:
   - meta.profile (invariant on profile value)
   - status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/compositionstatus-document-available-1" – edited short
   - subject (Reference type too open) – fixed with invariant 
   - author (Reference type too open) - fixed with invariant
   - attester.party (Reference type too open) - fixed with invariant
   - custodian (Reference type too open) - fixed with invariant
- The following features have been included:
   - canonical URL change (removing '4.0') has been proliferated - affects profiles Organization with Mandatory Identifier, Patient with Mandatory Identifier, My Health Record Patient, PractitionerRole with Mandatory Identifier
   - Metadata fixed: StructureDefinition.contact - node is missing
- removed wip known issues, added status terminology publication issue 
- Added draft implementation guidance + context

**Comment by dtr-agency** [comment]
Product owner walkthrough resulted in minor changes to context, and implementation guidance. Product owner now okayed content.

**Comment by dtr-agency** [comment]
Moving to internal review with @RichardTON

**Comment by dtr-agency** [comment]
Passed internal review.

**Comment by dtr-agency** [comment]
Merged, regenerated, and pushed to GitHub.
