### ISSUE TITLE
My Health Record Other Diagnostic Report

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#44]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
This profile is to define a short form representation providing a rich text representation of the report as issued by the diagnostic service provider with supporting key elements of clinical relevance for the electronic exchange of other diagnostic investigations (such as echo cardiogram or colonoscopy or hearing test) between healthcare providers and the My Health Record system infrastructure in Australia. 

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by SatyaYelisetti** [comment]
Shell profile of Atomic Pathology Report has been created and is currently under review.

**Comment by SatyaYelisetti** [comment]
Shell profile of My Health Record Other Diagnostic Report has been created and it can be found at the above commit

**Comment by dtr-agency** [comment]
The ValueSet design in #58 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1.

**Comment by dtr-agency** [comment]
Work started on phase 2; intending to:
- No 'work in progress' issues remain:
  - meta.profile (invariant on profile value)
  - status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1" – edited short
  - category is bound as extensible
   - subject (Reference type too open) – fixed with invariant 
  - performer (Reference type too open) - fixed with invariant
  - basedOn (ServiceReqeust.requester shall be PractitionerRole) - fixed with invariant
- The following features have been included:
  - canonical URL change (removing '4.0') has been proliferated - affects profiles Organization with Mandatory Identifier, Patient with Mandatory Identifier, My Health Record Patient, PractitionerRole with Mandatory Identifier
   - removed erroneous short on DiagnosticReport.presentedForm
   - added missing cardinality constraint 1..1 on basedOn.reference
   - added short to basedOn.reference
- removed wip known issues, added status terminology publication issue 
- Added draft implementation guidance + context

**Comment by dtr-agency** [comment]
Ready for product owner walkthrough.

**Comment by dtr-agency** [comment]
Product owner walkthrough held 19/06 - minor changes to known issue; added sentence to Boundaries and relationships. Product owner now okayed content.

**Comment by dtr-agency** [comment]
Moving to internal review with @RichardTON

**Comment by dtr-agency** [comment]
Fixed issues found in internal review, back with @RichardTON for confirmation.

**Comment by dtr-agency** [comment]
Passed internal review.
Merged, regenerated, and pushed to GitHub.
