### ISSUE TITLE
ImagingStudy - Diagnostic Imaging Study

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#52]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
This profile is to represent key elements of clinical relevance of an imaging study in a diagnostic imaging report context. This profile is intended to support the electronic exchange of diagnostic imaging reports between healthcare providers, and between healthcare providers and the My Health Record system infrastructure in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by SatyaYelisetti** [comment]
Shell profile of ImagingStudy (Diagnostic Imaging Study) can now be found at the above commit.

**Comment by dtr-agency** [comment]
Diagnostic Imaging Study phase 2:

- No 'work in progress' issues remain: subject (Reference type too open) – fixed with invariant
- The following features have been included: canonical URL change (removing '4.0') has been proliferated - affects profiles My Health Record Patient
- removed wip known issue, tidied up content to point to AU Base as that is where the content will be driven 
- Added draft implementation guidance + context

**Comment by dtr-agency** [comment]
Ready for joint review with Product Owner @davidmckillop and an internal review... hunting for one.

**Comment by dbojicic-agency** [comment]
In review with @dbojicic-agency.

**Comment by dbojicic-agency** [comment]
Reviewed, no issues found.

**Comment by dtr-agency** [comment]
Merged, regenerated, pushed to GitHub.
