### ISSUE TITLE
DiagnosticReport - Atomic Other Diagnostic Report

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#53]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue
## Change description
This profile is to define an atomic representation of a report as issued by the diagnostic service provider to support the electronic exchange of other diagnostic investigations (such as echo cardiogram or colonoscopy or hearing test) between healthcare providers in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by dtr-agency** [comment]
@davidmckillop, this is HL7?

**Comment by SatyaYelisetti** [comment]
Shell profile of Atomic Other Diagnostic Report has been created and is currently under review.

**Comment by SatyaYelisetti** [comment]
Shell profile of Atomic Other Diagnostic Report has been created and can be found via the above commit.

**Comment by dtr-agency** [comment]
The ValueSet design in #58 is now accepted and in publication schedule. Binding can occur using the agreed canonical uri: https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1.

**Comment by dtr-agency** [comment]
Work started on phase 2; intending to:
- No 'work in progress' issues remain:
   - meta.profile (invariant on profile value)
   - status is bound as required - uri = "https://healthterminologies.gov.au/fhir/ValueSet/diagnosticreportstatus-report-available-1" – edited short
   - subject (Reference type too open) – fixed with invariant 
   - performer (Reference type too open) - fixed with invariant
- The following features have been included:
   - canonical URL change (removing '4.0') has been proliferated - affects profiles Organization with Mandatory Identifier, Patient with Mandatory Identifier, My Health Record Patient, PractitionerRole with Mandatory Identifier
   - category is bound as extensible
- removed wip known issues, added status terminology publication issue 
- Added draft implementation guidance + context

**Comment by dtr-agency** [comment]
Product review leading to addition of profiles to result; fixes to implementation guidance; added short to basedOn.reference. Product owner now okayed content.

**Comment by dtr-agency** [comment]
Sent for internal review with @RichardTON.

**Comment by dtr-agency** [comment]
Passed internal review.

**Comment by dtr-agency** [comment]
Merged, rebuild output, and pushed to GitHub.
