### ISSUE TITLE
Pathology Report example - Full Blood Count plus ESR (atomic)

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#77]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
This example of a "Full Blood Count plus ESR" report is to present a pathology report with atomic data (observation) with and attached pdf. This report is a representation of a report issued by a diagnostic service provider with atomic content (observations with values) and elements of clinical relevance for the electronic exchange of pathology reports between healthcare providers in Australia.

## What it actually enables people to do
This example will enable developers to view the structure and content of a suitable pathology report with atomic content (observation(s) with value(s)) and an attached pdf that is suitable for the electronic exchange of pathology reports between healthcare providers in Australia.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## How awesome would it be?
Many developers find examples useful especially if one similar to their use case can be found i.e. the more and varied examples the better.

## Workarounds
A developer could always read the specification and Diagnostics implementation guide and develop their own content.

## Additional context
This example has 2 separate orderable tests with the Full Blood Count being a panel of tests and the ESR being a single test where both orderables are reported on the Full Blood Count report.

**Comment by dtr-agency** [comment]
The MHR (#66) and Atomic will be two flavours of the exact same report. So for elements included in both the same exact value is expected - there will be three main differences:
- MHR uses Bundle type=document with a Composition as the grouper
- Atomic will not be a Bundle - it will be included as a DiagnosticReport that references other content in a way that makes it easy to see the FHIR structure associated with the primary narrative rendering. Therefore this example is not constructed to show a packaged up instance of a payload on the wire, or how individual resources might reference each other in a server.
- Same patient, author, etc. (same values for the clinical/business elements that are present in both) but the elements included will differ (some added or removed between scenarios); and of course the technical elements will have different values e.g. unique ids as the ids are for the resources as entries into the Bundle not the business identifier or unique meta.lastUpdated etc.

**Comment by dtr-agency** [comment]
Created Atomic example in the referenced style with a DiagnosticReport as the grouper - fully aligned to MHR example.

This referenced style is a split-out set for implementers interested in looking at part using the generated narrative and meaningful phrase ids (e.g. 'e-a-ratio') to look at individual parts of the atomic instead of being presented with the bundle blob.  Most of the content is included with ids that relate to the content to assist in navigating to material and in a way that makes it easy to see the FHIR structure associated with the primary narrative rendering. Therefore this example is not constructed to show a packaged up instance of a payload on the wire, or how individual resources might reference each other in a server.

Example uses the example report G:\NEHTA Projects\CI\FHIR\FHIR IG\Diagnostics\Pathology\Examples\FBC-atomic replacing (as directed) all the entities plus adding ServiceRequest. Also corrected one of the values in the attachment to match the accompanying G:\NEHTA Projects\CI\FHIR\FHIR IG\Diagnostics\Pathology\Examples\FBC-atomic.

This use cases shows a single report with two primary observations: a FBC with an ESR. The FBC is a grouper only with child individual tests with values (the LOINC codes for the individual tests are all part of the LOINC panel 57782-5 that is the code used for the primary grouper FBC Obs.

DiagnosticReport.text demonstrates a rendering as close to the sample PDF as possible and contains some additional narrative.

**Comment by dtr-agency** [comment]
Ready for product owner walkthrough.

**Comment by dtr-agency** [comment]
Product owner okay in principle. Moving to internal review with @robeastwood-agency.

**Comment by dtr-agency** [comment]
Quick review completed and fixes confirmed.

**Comment by robeastwood-agency** [comment]
Internal review carried out with a handful of updates being made. Ready for merging into master branch.

**Comment by dtr-agency** [comment]
Merged, rebuilt, pushed to GitHub.
